name: Update Attributions Weekly

on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_6_*_*_*
    - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
