name: Weekly issue updates

on:
  schedule:
    # https://crontab.guru/#0_12_*_*_1
    - cron: "0 12 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      # Update all the translation issues on a nightly basis
      - run: yarn docs-sync update-github-issues microsoft/TypeScript-Website-Localizations
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Updates the attribution.json file in git    
      - uses: OSS-Docs-Tools/create-attribution-json@master
        with:
          glob: "docs/documentation/**/*.md"
      
      - name: Configure git and update attribution.json
        run: |
          git config user.email "bot@github.com"
          git config user.name "GitHub Bot"
          git add -f attribution.json
          if git commit -m "Update attribution.json"; then
            git push
          fi
